http:
  listener:
    host: "0.0.0.0"
    port: "9081"
    path: "/travelOnTipCall/{serviceType}"
    
db:
  oracle:
    host: "localhost"
    port: "1521"
    user: "SYSTEM"
    password: "dummy"
    instance: "xe"